# Generated by Django 5.0.6 on 2025-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=255)),
                ('debtor_phone', models.CharField(max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_products', models.CharField(max_length=255)),
                ('products_in_debt', models.CharField(max_length=255)),
                ('debt_pending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_products', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('lishe 3kg', 'Lishe 3kg'), ('lishe dozen', 'Lishe dozen'), ('Unga 25kg', 'Unga 25kg'), ('Unga 10kg', 'Unga 10kg'), ('Unga 5kg', 'Unga 5kg'), ('kande 25kg', 'Kande 25kg')], default='lishe', max_length=255)),
                ('image', models.ImageField(default='product.jpg', upload_to='user_directory_path')),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=999999999)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=999999999)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-date',),
            },
        ),
    ]
