# Generated by Django 4.2.11 on 2025-03-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=255, unique=True)),
                ('debtor_phone', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('lishe 3kg', 'Lishe 3kg'), ('lishe dozen', 'Lishe dozen'), ('Unga 25kg', 'Unga 25kg'), ('Unga 10kg', 'Unga 10kg'), ('Unga 5kg', 'Unga 5kg'), ('kande 25kg', 'Kande 25kg')], max_length=255, unique=True)),
                ('image', models.ImageField(default='product.jpg', upload_to='user_directory_path')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DebitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('debitor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.debitororder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.product')),
            ],
            options={
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
        migrations.AddField(
            model_name='debitororder',
            name='debitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.debtor'),
        ),
    ]
