# Generated by Django 5.0.6 on 2025-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='name_of_products',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='number_of_products',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='products_in_debt',
        ),
        migrations.AddField(
            model_name='debtor',
            name='products',
            field=models.ManyToManyField(to='ShibeApp.product'),
        ),
    ]
