# Generated by Django 5.1.4 on 2025-02-01 18:37

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=30, max_length=30, prefix='cat', unique=True)),
                ('title', models.CharField(default='category', max_length=200)),
                ('image', models.ImageField(default='category.jpg', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=30, max_length=30, prefix='cat', unique=True)),
                ('title', models.CharField(default='shibeunga', max_length=200)),
                ('image', models.ImageField(default='product.jpg', upload_to='user_directory_path')),
                ('description', models.TextField(blank=True, default='this is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=999999999)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=999999999)),
                ('specification', models.TextField(blank=True, null=True)),
                ('product_status', models.CharField(choices=[('add', 'Added'), ('remove', 'Removed'), ('delete', 'Deleted')], default='Added', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=30, prefix='sku', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShibeApp.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShibeApp.product')),
            ],
            options={
                'verbose_name_plural': 'Product_images',
            },
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=30, max_length=30, prefix='cat', unique=True)),
                ('title', models.CharField(default='shibesellers', max_length=200)),
                ('image', models.ImageField(default='seller.jpg', upload_to='user_directory_path')),
                ('description', models.TextField(blank=True, default='this is the seller', null=True)),
                ('entry_time', models.CharField(default='100', max_length=100)),
                ('contact', models.CharField(default='+255 745 989 250', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
