# Generated by Django 5.1.4 on 2025-02-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0002_category_product_productimage_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
