# Generated by Django 4.2.11 on 2025-03-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0002_alter_debtor_options_remove_debtor_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='balance',
        ),
    ]
