# Generated by Django 5.1.7 on 2025-03-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0002_remove_debtor_name_of_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='debt_paid',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='debt_pending',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='products',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='2.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.debtor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='DebitorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.debtor')),
            ],
            options={
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='DebitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('debitor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.debitororder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShibeApp.product')),
            ],
            options={
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
    ]
