# Generated by Django 5.1.4 on 2025-02-20 21:02

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0003_remove_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=33, max_length=33, prefix='cat', unique=True),
        ),
    ]
