# Generated by Django 4.2.11 on 2025-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0003_remove_debtor_debt_paid_remove_debtor_debt_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('lishe 3kg', 'Lishe 3kg'), ('lishe dozen', 'Lishe dozen'), ('Unga 25kg', 'Unga 25kg'), ('Unga 10kg', 'Unga 10kg'), ('Unga 5kg', 'Unga 5kg'), ('kande 25kg', 'Kande 25kg')], max_length=255),
        ),
    ]
