# Generated by Django 5.1.4 on 2025-02-20 21:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0004_alter_category_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=33, max_length=33, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=33, max_length=33, prefix='cat', unique=True),
        ),
    ]
