# Generated by Django 4.2.11 on 2025-03-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debtor_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
