# Generated by Django 5.1.4 on 2025-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0006_alter_product_pid_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=255)),
                ('debtor_phone', models.CharField(max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_products', models.CharField(max_length=255)),
                ('sum_of_debts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_in_debt', models.TextField()),
                ('debt_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_reduced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_overdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_pending', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
