# Generated by Django 4.2.11 on 2025-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShibeApp', '0006_alter_debtor_debtor_name_alter_debtor_debtor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debtor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_phone',
            field=models.CharField(max_length=20),
        ),
    ]
